version: '3'

services:
  postgres:
    image: postgres:14
    container_name: baql-db
    networks:
      - baql-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: baql_development
      POSTGRES_USER: baql_user
      POSTGRES_PASSWORD: rootpass

networks:
  baql-net:
